---

- name: Manage and Configure Workstation Dotfiles
  hosts: all
  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Print readiness message
      ansible.builtin.debug:
        msg: "System configuration is ready to start..."

    - name: Remove unneeded and bloatware applications
      ansible.builtin.include_tasks: roles/debloat.yml
      when: inventory_hostname in groups['Desktop']
      tags: debloat

    - name: Configure and enable required repositories
      ansible.builtin.include_tasks: roles/repo.yml
      tags: repo

    - name: Install required system packages
      ansible.builtin.include_tasks: roles/install.yml
      tags: install

    - name: Configure and enable Flatpak repositories
      ansible.builtin.include_tasks: roles/flatpak_repo.yml
      when: inventory_hostname in groups['Desktop']
      tags: flatpak-repo

    - name: Install required Flatpak applications
      ansible.builtin.include_tasks: roles/flatpak_install.yml
      when: inventory_hostname in groups['Desktop']
      tags: flatpak-install

    - name: Check and configure NVIDIA drivers on Fedora
      ansible.builtin.include_tasks: roles/nvidia.yml
      tags: Nvidia

    - name: Enable systemd services
      ansible.builtin.include_tasks: roles/systemd.yml
      tags: systemd

    - name: Manage and sync user dotfiles
      ansible.builtin.include_tasks: roles/dotfiles.yml
      tags: dotfiles

    - name: Enable pal cloudy stack
      ansible.builtin.include_tasks: roles/pal-cloudy-stack.yml
      tags: stack
      when: inventory_hostname in groups['Servers']

    - name: enable ssh key
      ansible.builtin.include_tasks: roles/ssh_keys.yml
      when: 
        - inventory_hostname in groups['Desktop']
        - ansible_facts['hostname'] == "cutie"
      tags: ssh

    - name: enable GPG keys
      ansible.builtin.include_tasks: roles/gpg_keys.yml
      when: 
        - inventory_hostname in groups['Desktop']
        - ansible_facts['hostname'] == "cutie"
      tags: gpg

    - name: configure snapper snapshots
      ansible.builtin.include_tasks: roles/snapper.yml
      when:
        - inventory_hostname in groups['Desktop']
        - ansible_facts['distribution'] == "Fedora"
        - ansible_facts['hostname'] == "cutie"
      tags: snapper

