---

- name: debloat for fedora
  dnf:
    name:
      - gnome-calendar
      - gnome-contacts
      - gnome-calculator
      - gnome-clocks
      - mediawriter
      - totem
      - sushi
      - evince
      - simple-scan
      - snapshot
      - gnome-maps
      - gnome-boxes
      - gnome-characters
      - gnome-connections
      - loupe
      - gnome-tour
      - rhythmbox
      - anaconda-live
      - anaconda-webui
      - firefox-langpacks
      - firefox
      - showtime
      - decibels
      - papers
      - gnome-terminal
      - unoconv
      - libreoffice-*
    state: absent
  any_errors_fatal: true
  when:
    - ansible_facts['distribution'] == "Fedora"
    - inventory_hostname in groups['Desktop']
  become: true
