---

- name: Copy system configuration files {Desktop}
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"

  become: true
  with_items:
    - { src: "system/dnf/dnf.conf", dest: "/etc/dnf/dnf.conf" }
    - {
        src: "system/systemd-resolve/resolved.conf",
        dest: "/etc/systemd/resolved.conf",
      }
  when:
    - inventory_hostname in groups['Desktop']
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Copy system configuration files {Servers}
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"

  become: true
  with_items:
    - { src: "system/fail2ban/jail.local", dest: "/etc/fail2ban/jail.local" }
  when:
    - inventory_hostname in groups['Servers']
    - ansible_facts['hostname'] == "violet-1"


- name: Ensure target config directories exist
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/helix"
    state: directory
    mode: "0755"
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Copy user home dotfiles
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ item.dest }}"
    mode: "0644"

  with_items:
    - { src: "home/bash/.bashrc", dest: ".bashrc" }
    - { src: "home/vim/.vimrc", dest: ".vimrc" }
    - { src: "home/git/.gitconfig", dest: ".gitconfig" }
    - { src: "home/helix/config.toml", dest: ".config/helix/config.toml" }
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Settings the background for gnome
  ansible.builtin.command: "{{ item }}"

  loop:
    - "gsettings set org.gnome.desktop.screensaver picture-uri file:///'{{ ansible_facts.env.PWD }}/assets/wallpaper/Wallpaper_2.png'"
    - "gsettings set org.gnome.desktop.background picture-uri file:///'{{ ansible_facts.env.PWD }}/assets/wallpaper/Wallpaper_2.png'"
    - "gsettings set org.gnome.desktop.background picture-uri-dark file:///'{{ ansible_facts.env.PWD }}/assets/wallpaper/Wallpaper_2.png'"
  when:
    - inventory_hostname in groups['Desktop']
    - ansible_facts['env']['XDG_CURRENT_DESKTOP'] == "GNOME"
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Settings the tailscale for violet-1{Server}
  ansible.builtin.command: "tailscale up --auth-key={{ violet_one_tailscale_key }} --ssh --advertise-exit-node"
  become: true
  when:
    - inventory_hostname in groups['Servers']

- name: Settings the tailscale for cutie{Desktop}
  ansible.builtin.command: "tailscale up --auth-key={{ cutie_tailscale_key }} --advertise-exit-node --operator={{ ansible_facts['user_id'] }}"
  become: true
  when:
    - inventory_hostname in groups['Desktop']