---

- name: Flatpak app install
  flatpak:
    name:
      - com.usebottles.bottles
      - com.github.rafostar.Clapper
      - io.gitlab.theevilskeleton.Upscaler
      - org.localsend.localsend_app
      - org.mozilla.thunderbird
      - io.gitlab.librewolf-community
      - com.github.tchx84.Flatseal
      - com.github.wwmm.easyeffects
      - org.torproject.torbrowser-launcher
      - org.gnome.Loupe
      - io.ente.auth
      - dev.deedles.Trayscale
      - org.gnome.seahorse.Application
      - io.github.giantpinkrobots.varia
      - dev.vencord.Vesktop
      - com.mattjakeman.ExtensionManager
      - md.obsidian.Obsidian
      - org.inkscape.Inkscape
    state: present
    remote: flathub
    method: user

  any_errors_fatal: true
  when:
    - inventory_hostname in groups['Desktop']
