---

- name: check the Flatpak
  ansible.builtin.command: which flatpak
  register: flatpak_check
  ignore_errors: true
  changed_when: false

- name: Flatpak setup
  package:
    name: flatpak
  when: flatpak_check.rc != 0

- name: Add Flathub Repo
  flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: false
  when:
    - inventory_hostname in groups['Desktop']
