---
- name: install for cutie {fedora}
  dnf:
    name:
      - git
      - git-lfs
      - vim
      - flatpak
      - podman
      - podman-docker
      - podman-compose
      - firewalld
      - firewall-config
      - firewall-applet
      - gnome-tweaks
      - papirus-icon-theme
      - ptyxis
      - helix
      - cargo
      - btop
      - wtype
      - fuse
      - "@virtualization"
      - fuse-libs
      - snapper
      - python3-dnf-plugin-snapper
      - btrfs-assistant
      - freerdp
      - gtk-layer-shell
      - rustup
      - golang
      - bat
      - ansible
      - ansible-lint
      - tailscale
      - conda
      - unityhub
      - jetbrains-toolbox
    state: present

  any_errors_fatal: true
  when:
    - ansible_facts['distribution'] in ['Fedora']
    - inventory_hostname in groups['Desktop']
  become: true

- name: install for cutie {Rocky} not ready
  dnf:
    name:
      - git
      - git-lfs
      - vim
#      - flatpak
#      - podman
#      - podman-docker
#      - podman-compose
#      - firewalld
#      - firewall-config
#      - firewall-applet
#      - gnome-tweaks
#      - papirus-icon-theme
#      - ptyxis
#      - helix
#      - cargo
#      - btop
#      - wtype
#      - fuse
#      - fuse-libs
#      - snapper
#      - python3-dnf-plugin-snapper
#      - btrfs-assistant
#      - freerdp
#      - gtk-layer-shell
#      - rustup
#      - golang
#      - bat
#      - ansible
#      - ansible-lint
#      - tailscale
#      - conda
#      - unityhub
#      - jetbrains-toolbox
    state: present

  any_errors_fatal: true
  when:
    - ansible_facts['distribution'] in ['Rocky']
    - inventory_hostname in groups['Desktop']
  become: true

- name: install rust lang~ for cutie (Desktop)
  ansible.builtin.command: "rustup-init --profile default --default-toolchain stable --default-host x86_64-unknown-linux-gnu -y"
  when:
    - inventory_hostname in groups['Desktop']
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: install for violet-1 (server{fedora})
  dnf:
    name:
      - git
      - git-lfs
      - podman
      - podman-docker
      - podman-compose
      - firewalld
      - helix
      - snapper
      - python3-dnf-plugin-snapper
      - tailscale
      - node-exporter
      - bat
      - btop
      - cockpit
      - cockpit-files
      - cockpit-session-recording
      - cockpit-selinux
      - cockpit-podman
      - cockpit-ws
      - cockpit-ws-selinux
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-storaged
      - fail2ban
      - curl
      - wget

    state: present

  any_errors_fatal: true
  when:
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']
    - inventory_hostname in groups['Servers']
  become: true
