---

- name: install pal-cloudy-stack with git
  ansible.builtin.git:
    repo: https://gitlab.com/FluffyPal/pal-clouddyy-stack.git
    dest: "{{ ansible_facts['env']['HOME'] }}/pal-clouddyy-stack"

- name: Remove unnecessary services in docker-compose.yml
  ansible.builtin.replace:
    path: "{{ ansible_facts['env']['HOME'] }}/pal-clouddyy-stack/docker-compose.yml"
    regexp: '{{ item.source }}'
    replace: '{{ item.target }}'
  loop:
    - { source: '^(\s*)-\s*\./nextcloud/docker-compose\.yml' , target: '\1# - ./nextcloud/docker-compose.yml'}
    - { source: '^(\s*)-\s*\./palisch/docker-compose\.yml' , target: '\1# - ./palisch/docker-compose.yml' }
    - { source: '^(\s*)-\s*\./linkstack/docker-compose\.yml' , target: '\1# - ./linkstack/docker-compose.yml' }
    - { source: '^(\s*)-\s*\./tailscale/docker-compose\.yml' , target: '\1# - ./tailscale/docker-compose.yml' }
    - { source: '^(\s*)-\s*\./mattermost/docker-compose\.yml' , target: '\1# - ./mattermost/docker-compose.yml' }
    - { source: '^(\s*)-\s*\./torrelay/docker-compose\.yml' , target: '\1# - ./torrelay/docker-compose.yml' }

- name: enable podman-restart user service
  ansible.builtin.systemd:
    name: podman-restart.service
    scope: user
    enabled: true
    state: started

- name: check linger status
  ansible.builtin.command: loginctl show-user {{ ansible_facts.user_id }} -p Linger --value
  register: linger_status

- name: enable linger
  ansible.builtin.command: loginctl enable-linger {{ ansible_facts.user_id }}
  become: true
  when: linger_status.stdout != "yes"
