---

- name: Configure RPM Fusion (Free and Non-Free) repositories on Fedora
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true
  when: ansible_facts['distribution'] in ['Fedora']

- name: Install epel-release package on Rocky
  dnf:
    name: epel-release
    state: present
  become: true
  when: ansible_facts['distribution'] in ['Rocky']

- name: Install elrepo-release package on Rocky
  dnf:
    name: elrepo-release
    state: present
  become: true
  when: ansible_facts['distribution'] in ['Rocky']

- name: Enable crb on Rocky
  ansible.builtin.shell: "dnf config-manager --set-enabled crb"
  become: true
  when: ansible_facts['distribution'] in ['Rocky']

- name: Configure RPM Fusion (Free and Non-Free) repositories on Rocky
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true
  when: ansible_facts['distribution'] in ['Rocky']

- name: Add Terra repository on Fedora
  ansible.builtin.yum_repository:
    name: terra
    description: Terra Repository for Fedora
    baseurl: "https://repos.fyralabs.com/terra{{ ansible_facts['distribution_major_version'] }}"
    gpgcheck: false
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Add NVIDIA Container Toolkit repository on Fedora
  ansible.builtin.yum_repository:
    name: nvidia-container-toolkit
    description: Nvidia container toolkit Repository for Fedora
    baseurl: "https://nvidia.github.io/libnvidia-container/stable/rpm/$basearch"
    gpgcheck: true
    gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Install terra-release package on Fedora
  dnf:
    name: terra-release
    state: present
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Add Antigravity RPM repository on Fedora
  ansible.builtin.yum_repository:
    name: antigravity-rpm
    description: Antigravity RPM Repository
    baseurl: https://us-central1-yum.pkg.dev/projects/antigravity-auto-updater-dev/antigravity-rpm
    enabled: true
    gpgcheck: false
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Add Pal repository on Fedora
  ansible.builtin.yum_repository:
    name: pal-repository
    description: Pal RPM Repository
    baseurl: https://repository.fluffypal.me
    enabled: true
    gpgcheck: false
  become: true
  when: 
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']
    - inventory_hostname in groups['Desktop']
  
- name: Add VS Code RPM repository on Fedora
  ansible.builtin.yum_repository:
    name: Visual-Studio-Code
    description: Vscode RPM Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Add google chrome RPM repository on Fedora
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google chrome RPM Repository
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']

- name: Add Unity Hub RPM repository on Fedora
  ansible.builtin.yum_repository:
    name: unityhub
    description: Unity Hub RPM Repository
    baseurl: https://hub.unity3d.com/linux/repos/rpm/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key
  become: true
  when: ansible_facts['distribution'] in ['Fedora', 'Rocky']