---
- name: Enable and start the Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  become: true

- name: Enable and start the node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
  when:
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']
    - inventory_hostname in groups['Servers']
  become: true

- name: Enable and start the cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
  when:
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']
    - inventory_hostname in groups['Servers']
  become: true

- name: Enable and start the fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
  become: true
  when:
    - inventory_hostname in groups['Servers']

- name: Enable and start the user mode Podman socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    state: started
    scope: user
  when:
    - inventory_hostname in groups['Servers']

- name: Configure system parameters and earldom on cutie
  block:
    - name: Set swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '133'
        state: present
        sysctl_file: /etc/sysctl.d/99-swappiness.conf
        reload: true

    - name: Disable and stop systemd-oomd
      ansible.builtin.systemd:
        name: systemd-oomd
        state: stopped
        enabled: false

    - name: Ensure earlyoom is installed
      ansible.builtin.dnf:
        name: earlyoom
        state: present

    - name: Create systemd drop-in directory for earlyoom
      ansible.builtin.file:
        path: /etc/systemd/system/earlyoom.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure earlyoom arguments (e.g., trigger at 15% RAM and 15% Swap)
      ansible.builtin.copy:
        dest: /etc/systemd/system/earlyoom.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/earlyoom -r 15 -s 15
        owner: root
        group: root
        mode: '0644'
      register: earlyoom_config

    - name: Start and enable earlyoom
      ansible.builtin.systemd:
        name: earlyoom
        state: "{{ 'restarted' if earlyoom_config.changed else 'started' }}"
        enabled: true
        daemon_reload: true
  become: true
  when:
    - inventory_hostname in groups['Desktop']
    - ansible_facts['distribution'] in ['Fedora', 'Rocky']
    - ansible_facts['hostname'] == "cutie"