---
- name: Enable and start the tailscaled service
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  become: true

- name: Enable and start the node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['hostname'] == "violet-1"
  become: true

- name: Enable and start the cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['hostname'] == "violet-1"
  become: true

- name: Enable and start the fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
  become: true
  when:
    - inventory_hostname in groups['Servers']
    - ansible_facts['hostname'] == "violet-1"